proagain/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testapp/urls.py
from django.urls import path
from django.conf.urls import url
from testapp import views
app_name = "testapp"
urlpatterns = [
    path('', views.homeview, name='home'),
    path('about/', views.aboutview, name='about'),
    path('clippingpaths/', views.clippingpathsview, name='clipping_paths'),
    path('backgroundremover/', views.background_remover_view, name='background_remover'),
    path('colorcorrection/', views.color_correction_view, name='color_correction'),
    path('dropshadow/', views.drop_shadow_view, name='drop_shadow'),
    path('imageretuch/', views.image_retuch_view, name='image_retuch'),
    path('invisiblemannequine/', views.invisible_mannequine_view, name='invisble_mannequine'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('pricing/', views.pricing, name='pricing'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact, name='contact'),
    path('getfreedemo/', views.getfredemo, name='getfreedemo'),
    path('bloglist/', views.bloglist, name='bloglist'),
    path('blogdetails/', views.blogdetails, name='blogdetails'),

] 

testapp/models.py
from django.db import models

# Create your models here.

testapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def homeview(request):
    return render(request, 'testapp/index.html')


def aboutview(request):
    return render(request, 'testapp/about.html')

def clippingpathsview(request):
    return render(request, 'testapp/clipping_path.html')

def background_remover_view(request):
    return render(request, 'testapp/background_remover.html')

def color_correction_view(request):
    return render(request, 'testapp/color_correction.html')

def drop_shadow_view(request):
    return render(request, 'testapp/drop_shadow.html')

def image_retuch_view(request):
    return render(request, 'testapp/image_retuch.html')

def invisible_mannequine_view(request):
    return render(request, 'testapp/invisible_mannequin.html')


def portfolio(request):
    return render(request, 'testapp/portfolio.html')

def pricing(request):
    return render(request, 'testapp/pricing.html')

def faq(request):
    return render(request, 'testapp/faq.html')


def contact(request):
    return render(request, 'testapp/contact.html')


def getfredemo(request):
    return render(request, 'testapp/get_free_demo.html')


def bloglist(request):
    return render(request, 'testapp/blog_list.html')


def blogdetails(request):
    return render(request, 'testapp/blog_detail.html')

templates/testapp/about.html
{% extends 'testapp/base.html' %}
{% load static %}
{% block title %} about {% endblock %}

{% block content %}
<section class="background_image py-5">
  <div class="container">
      <div class="text-white text-center">
        <h1 class="display-1 txt_shadow" style="font-weight: 800; font-size: 6vh;">About Clipping Paths India </h1><br>
        <button type="button" class="btn btn-danger btn-lg m-2 rounded-pill"><a href="#" class="text-white"><b> Our Expertise</b></a></button>
        <button type="button" class="btn btn-light btn-lg m-2 rounded-pill"><a href="{% url 'testapp:contact' %}" class="text_color"><b> Get Contact Us</b></a></button>
    </div>
  </div>
</section>

<section class="py-5">
<div class="container">
  <div class="text-size txt_shadow text-center">
    <h2>KNOW ABOUT OUR PROFESSIONAL QUALITY</h2><hr>
  </div>
  <div class="row pt-3">
    <div class="col-sm-3 col-md-3"> 
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/24-hours-support.png' %}" class="img-fluid" title="24 hours support" alt="24 hours support"><br><br>
        <h4>24/7 We're Open</h4>
        <p>We’re always ready to provide our professional quality services to you by clipping path India service.</p>
      </div>
    </div>
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/lock.png' %}" class="img-fluid" title="100% Secured Files" alt="100% Secured Files"><br><br>
        <h4>100% Secured Files</h4>
        <p>When you give us your desired photo, we don’t share that.</p>
      </div>
    </div>
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/customer-satisfaction.png' %}" class="img-fluid" title="100% Client Satisfaction" alt="100% Client Satisfaction"><br><br>
        <h4>100% Client Satisfaction</h4>
        <p>We are a satisfying service provider ensuring 100% Satisfaction.</p>
      </div>
    </div>
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/on-time.png' %}" class="img-fluid" title="On Time Delivery" alt="On Time Delivery"><br><br>
        <h4>On Time Delivery</h4>
        <p>We turn around 100% on time. You don’t have to wait for your surprise.</p>
      </div>
    </div>
  </div><br>
  <div class="txt_shadow text-center">
    <h4>Clipping Paths India (CPIn) is one of the best clipping path service provider on the earth. We always offer satisfactory guaranteed work for our client and do every work as own work with carefully.</h4><br>
    <h4>We offer a wide range of image editing services such as Clipping Path, Background Remove, Image Masking, Photo Retouching, Shadow Creating, Multiple Clipping Path, Image Manipulation, Color Correction, Web Image Optimization With a perfect blend of experience, skill, dedication, and punctuality. We are different from others because we always maintain high quality work at affordable price. And our specialty is that, we are 24/7 available in 365 days also we believe that client is always right.</h4>
  </div> <hr><br>

  <div class="text-size txt_shadow text-center">
    <h2>OUR TEAM</h2>
  </div><br>
  <div class="row">
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/1.-Mohammed-Nur-Ahmmed.jpg' %}" class="img-fluid" alt="">
        <h5 class="pt-1">Mohammad Nur Ahmed</h5>
        <p><span class="text-primary"> Chief Executive Officer(CEO)</span> <br>Clipping Paths India (CPIn) </p>
      </div>
    </div>
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/5.-Farhad-Bhuiyan.jpg' %}" class="img-fluid" alt="">
        <h5 class="pt-1">Farhad Bhuiyan</h5>
        <p><span class="text-primary">Executive Marketing (Asia)</span> <br>Clipping Paths India (CPIn) </p>
      </div>
    </div>
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/3.-Mujahidul-Islam.jpg' %}" class="img-fluid" alt="">
        <h5 class="pt-1">Mujahidul Islam </h5>
        <p><span class="text-primary"> Executive Director (Production)</span> <br>Clipping Paths India (CPIn) </p>
      </div>
    </div>
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/4.-Nur-Uddin-Fahim.jpg' %}" class="img-fluid" alt="">
        <h5 class="pt-1">Nur Uddin Fahim</h5>
        <p><span class="text-primary">Executive Director (Finance)</span> <br>Clipping Paths India (CPIn) </p>
      </div>
    </div>
    <div class="col-sm-3 col-md-3">
      <div class="text-center p-2">
        <img src="{% static 'theme/assets/img/about/2.-Md-Ariful-Islam.jpg' %}" class="img-fluid" alt="">
        <h5 class="pt-1">Ariful Islam</h5>
        <p><span class="text-primary">Executive Marketing (USA)</span> <br>Clipping Paths India (CPIn) </p>
      </div>
    </div>
   
  </div>

</div>
</section>


<section class=" py-5">
<div class="container">
    <div class="row">
      <div class="col-sm-3 col-md-3">
        <div class="text-center p-2">
          <img src="{% static 'theme/assets/img/about/innovative-ideas.png' %}" class="img-fluid" title="24 hours support" alt="24 hours support"><br><br>
          <h4>INNOVATIVE IDEAS</h4>
        </div>
      </div>
      <div class="col-sm-3 col-md-3">
        <div class="text-center p-2">
          <img src="{% static 'theme/assets/img/about/timely-supports.png' %}" class="img-fluid" title="timely supports" alt="timely supports"><br><br>
          <h4>TIMELY SUPPORT</h4>
        </div>
      </div>
      <div class="col-sm-3 col-md-3">
        <div class="text-center p-2">
          <img src="{% static 'theme/assets/img/about/advanched-technologies.png' %}" class="img-fluid" title="ADVANCED TECHNOLOGY" alt="ADVANCED TECHNOLOGY"><br><br>
          <h4>ADVANCED TECHNOLOGY</h4>
        </div>
      </div>
      <div class="col-sm-3 col-md-3">
        <div class="text-center p-2">
          <img src="{% static 'theme/assets/img/about/Clear-communication.png' %}" class="img-fluid" title="Clear Communication" alt="Clear Communication"><br><br>
          <h4>CLEAR COMMUNICATION</h4>
        </div>
      </div>
    </div>
</div>
</section>


{% endblock content %}
 

templates/testapp/background_remover.html
{% extends 'testapp/base.html' %}
{% load static %}
{% block title %}Background Remover{% endblock %}

{% block content %}
  <section class="background_image py-5">
    <div class="container">
        <div class="text-white text-center">
          <h1 class="display-1 txt_shadow" style="font-weight: 800; font-size: 6vh;">AFFORDABLE BACKGROUND REMOVE SERVICE</h1><br>
          <button type="button" class="btn btn-danger btn-lg m-2 rounded-pill"><a href="#" class="text-white"><b> Our Expertise</b></a></button>
            <button type="button" class="btn btn-light btn-lg m-2 rounded-pill"><a href="{% url 'testapp:contact' %}" class="text_color"><b> Get Contact Us</b></a></button>
      </div>
    </div>
</section>

<section>
  <div class="container"><br>
    <div class="text-center shadow p-3">
      <img src="{% static 'theme/assets/img/clipping-path/Background-remove_CPIn.jpg' %}" class="img-fluid" title="clipping path india" alt="clippiing path india">
    </div><br>
    <div class="txt-sz-p p-3">
      <p>
        There is no question that a photograph is incredibly valuable to each business. A great photo can make a memorable ad, brochure, website, or advertisement. Every company needs professional photo editing services to make the most of their photographs before putting them to print or digital platforms. That’s where the clipping path India comes in, providing tips and techniques for creating better images.</p><br>
      <p>Clipping path India edits your photo background remove it in various ways. image masking, remove background, resizing image clipping for fashion magazine ads, editing any image for commercial use and marketplace like amazon.</p><br>
    </div>
  </div><br>
</section>


<section>
  <div class="container">
    <div class="p-3 txt-sz-p">
      <h2 class="txt_shadow">Why need Background remove service</h2><br>
      <p>Background removal can remove the background from images to make them more appealing or complete. Some people look at a picture and immediately know what kind of picture it is. Others need to see what the background contains before making up their mind about it.</p><br>
      <p>There are hundreds, if not thousands, of applications out there, and you need to decide which one fulfills your needs best. Most people want the best quality backgrounds for their marketing projects even if it costs more.</p><br>
      <p>If your business deals with customers or visitors all over the world, or if your images are used by various media sources such as newspapers and magazines, you need background removing services provided by state-of-the-art technology.</p><br>
      <p>This has benefits like saving time, making the picture clearer, and allowing you to check out details better without having to check out the full photo.</p>
    </div>
     <br>
    <div class="p-3 txt-sz-p">
         <h3>Here are some features for what you need: a professional background remove service to outsource.</h3>
         <h4>Background remove to make your image perfect</h4><br>
        <p>
          Background removal services remove backgrounds from pictures in order to make them more memorable. These services create custom images using various picture editing tools such as GIMP or Photoshop.</p>  <br>
        <p>By using these services, you can change the appearance of your photos in a very short time period without having to go through the trouble of making your own images or waiting for images that might be already made. Background removal services are a good option if you want to change some important aspects of your picture without messing up the rest of it.</p><br>
        <h4>This service can save you time and money</h4>
        <p>Background removal is a great way to make even unprofessional-looking product photographs look professional and appealing. By outsourcing this type of work, you won’t have to waste time getting professional backgrounds from large companies that charge exorbitant amounts of money. You can instead work with someone who will do it for you at a price that’s comparable or less than what you’d pay if you did it yourself.</p><br>
        <p>By outsourcing your background removal services, you can focus on other tasks such as your marketing campaigns, business development, and customer support.</p><br>
        <h4>To highlight the main content image or text</h4>
        <p>This service can improve the overall quality of the product image by removing distracting background elements from the shot and focusing on the main content image or text.</p>
        <p>It’s great for visual branding, especially on product pages or blog posts. <br> After all, pure content always attracts the most attention.</p><br><br>
        <h4>To hide the unwanted parts from original images</h4>
        <p> Background removal services from photography can help you remove background elements from your pictures, particularly distracting or irrelevant ones.</p>
        <p>Remove unwanted elements from your products make the picture as clear as you like. The results can be stunning! </p><br><br>
        <h4>To make your image stand out from the crowd</h4>
        <p>Background removal service can be used to remove all sorts of background elements from your pictures. It’s a great service for those who want their product or photo to stand out more on the internet. Most importantly it improves the overall quality of your product photography, making sure that the focus of the viewer’s attention remains on the final product.</p><br><br>
        <h4>To improve the appearance of an image (make it look better)</h4>
        <p>The use of these services will enhance the overall look of your product photographs and give the owner of that product more options to enhance their appearance. The use of these services will increase the conversion rate when customers engage with your product.</p>
        <p>It is important to note that background removal services are provided in good faith and are only used for professional purposes.</p><br><br>
        <h4>Make your images match brand colors</h4>
        <p>Background removal services from photo or product photography are really important when your business grows and you are looking for businesses to do marketing for you.</p>
        <p>This service isn’t always necessary but it helps improve your overall brand image. When someone sees your photo or product, they can instantly associate it with what you do. That means you can get more potential customers and increase sales by removing background clutter so your photo or product looks as good as it can in the moments before your customer sees it.</p>
    </div>
    <br>
  </div>
</section>

<section class="why-choose-us">
  <div class="container">
    <div class="p-3 txt-sz-p">
      <h2 class="txt_shadow">Why Choose Us?</h2><br>
      <p>A company will never be able to cover all your needs, but at least you’ll have a chance to buy professional images which are of top quality and suitable for all situations.</p><br>
      <p>We are a professional photo editing company and our professional image editing team that allows one to quickly remove background and decoration elements from any image and bring it to life in a way that makes the viewer feel it has been well pictures taken. We can offer you clipping services which will give your pictures a fresh look.</p>
      <p>Let’s say you’re a customer and you’re looking for a good clipping path service provider. There are many companies out there offering this service but what makes us shine is that we provide a better value for our customers. Not only that but all of our work is done with utmost professionalism and integrity; you can trust that our team has studied the most recent trends in marketing and graphic design along with the latest industry best practices.</p><br>
      <p>We offer you quality services at affordable prices. Our professional team of professional remove artists provides you with professional-grade image background removal, crisp, and smart. We have a wide variety of backgrounds to choose from.</p><br>
      <p>Each of our backgrounds is handpicked from our vast database of high-quality stock images. We also ensure that all of our designs are custom-made to your specific needs. All you have to do is choose your background and add it to your project! If you are looking for something truly unique and artistic, you are surely in the right place.</p>
      <p>What are you waiting for? <br><br>

        Call us today for your Background removal service.</p>
    </div>
  </div>
</section>

<section class="bg-light py-5">
  <div class="container">
    <div class="text-center txt-sz-p">
      <h3 class="text-size txt_shadow">PRICING</h3>
      <p>Clipping Paths India (CPIn) is a unique image editing company. We never think about pricing. Our main concentration is the quality of work and our 1st goal is to show the quality of work and buildup a long-term business relationship.</p>
    </div><br>
    <div class="row">
        <div class="col-sm-6 col-md-6">
          <div class="py-5 p-3 border text-center bg-white txt-sz-p shadow">
            <h3 class="pt-3">STARTER</h3>
            <h1 class="display-1 txt_shadow" style="font-weight: 500; font-size: 10vh;">$0.29</h1>
            <p>/Per Image</p>
            <p class="border-bottom">Basic Plan For Beginners.</p><br>
            <p><b>10 Image/$10</b>  Minimum Order</p>
            <p> <b>2 Images Free</b> Trial Before Ordering</p>            
            <p><b>JPEG, PNG, PSD, TIFF</b>  Format</p>   
            <p><b>24/7 </b> Support</p> 
            <p><b> 3 Times</b> Revision </p>  
            <p> <b>Affiliate</b> Opportunities</p> 
            <p> <b>C To C Contact</b> Not Required</p>
            <p> <b>No Monthly</b> Payment System</p><br>
            <button type="button" class="btn border shadow btn-lg m-2"><a href="#"><b>Free Trial</b></a></button>
          </div>
        </div>
        <div class="col-sm-6 col-md-6">
          <div class="py-5 p-3 border text-center bg-white txt-sz-p shadow">
            <h3 class="pt-3 text-info">PROFESSIONAL</h3>
            <h1 class="display-1 txt_shadow" style="font-weight: 500; font-size: 10vh;">$0.21</h1>
            <p>/Per Image</p>
            <p class="border-bottom">Perfect For Professionals & Businesses.</p><br>
            <p><b>100 Image</b> Minimum Order </p>
            <p> <b> 3 Images Free</b> Trial Before Ordering</p>   
            <p><b>JPEG, PNG, PSD, TIFF, RAW, PDF</b>  Format</p>   
            <p>24/7 Support</p> 
            <p><b> Unlimited</b> Revision </p>  
            <p> <b>Affiliate</b> Opportunities</p> 
            <p> <b>C To C Contact</b> Not Required</p>
            <p> <b>Monthly</b> Payment System</p><br>
            <a class="btn footer-background text-white btn-lg button_slide shadow" href="{% url 'testapp:getfreedemo' %}" role="button">FREE TRIAL</a>
          </div>
        </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/testapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'theme/assets/img/favicon.PNG' %}" type="image/gif" sizes="16x16">
    <title>{% block title %}best clippingpath service in the world {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'theme/assets/clipping.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light border-bottom">
    <div class="container">
      <a class="navbar-brand" href="{% url 'testapp:home' %}"><img src="{% static 'theme/assets/img/clippingpathsindia.png' %}" class="img-fluid" height="93" width="275" title="clipping paths india" alt="clipping paths india"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'testapp:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'testapp:about' %}">About Us</a> </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Services
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item my-2 p-2" href="{% url 'testapp:clipping_paths' %}"><i class="fa fa-clipboard" aria-hidden="true"></i>&nbsp; Clipping Path</a>
              <a class="dropdown-item my-2 p-2" href="{% url 'testapp:background_remover' %}"><i class="fa fa-window-restore" aria-hidden="true"></i>&nbsp; Background Remover</a>
              <a class="dropdown-item my-2 p-2" href="{% url 'testapp:color_correction' %}"><i class="fa fa-adjust" aria-hidden="true"></i>&nbsp; Color Correction</a>
              <a class="dropdown-item my-2 p-2" href="{% url 'testapp:drop_shadow' %}"><i class="fa fa-clone" aria-hidden="true"></i>&nbsp; Drop Shadow</a>
              <a class="dropdown-item my-2 p-2" href="{% url 'testapp:image_retuch' %}"><i class="fa fa-picture-o" aria-hidden="true"></i>&nbsp;  Image Re-tuch</a>
              <a class="dropdown-item my-2 p-2" href="{% url 'testapp:invisble_mannequine' %}"><i class="fa fa-eye-slash" aria-hidden="true"></i>&nbsp;  Invisible Mannequin</a>
            </div>
          </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'testapp:portfolio' %}">Portfolio </a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'testapp:pricing' %}">Pricing </a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'testapp:contact' %}">Contact Us</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'testapp:getfreedemo' %}">Get Free Demo</a></li>
        </ul>
        <form class="form-inline my-1 my-lg-0">
          <a class="btn footer-background text-white btn-lg button_slide shadow" href="{% url 'testapp:getfreedemo' %}" role="button">Get Quote</a>
        </form>
      </div>
    </div>
  </nav>


{% block content %}

{% endblock content %}


<!-- footer -->
<section class="footer footer-background py-5">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-8">
        <div class="text-white">
          <h5>About Us</h5>
          <h2>CALL: +8801842130715</h2>
          <h5>EMAIL: CLIPPINGPATHSINDIA@GMAIL.COM</h5>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="text-white text-right">
        <img src="{% static 'theme/assets/img/clippingpathsindia.png' %}" class="img-fluid"  alt="Clipping Path India">
        </div>
      </div>
    </div><br><br>
    <div class="row border-bottom pb-3">
      <div class="col-sm-3 col-md-3">
        <div class="text-white p-2">
          <h5>SERVICES</h5>
            <a class="dropdown-item text-warning" href="{% url 'testapp:clipping_paths' %}"><i class="fa fa-clipboard" aria-hidden="true"></i>&nbsp; Clipping Path</a>
            <a class="dropdown-item text-warning" href="{% url 'testapp:background_remover' %}"><i class="fa fa-window-restore" aria-hidden="true"></i>&nbsp; Background Remover</a>
            <a class="dropdown-item text-warning" href="{% url 'testapp:color_correction' %}"><i class="fa fa-adjust" aria-hidden="true"></i>&nbsp; Color Correction</a>
            <a class="dropdown-item text-warning" href="{% url 'testapp:drop_shadow' %}"><i class="fa fa-clone" aria-hidden="true"></i>&nbsp; Drop Shadow</a>
            <a class="dropdown-item text-warning" href="{% url 'testapp:image_retuch' %}"><i class="fa fa-picture-o" aria-hidden="true"></i>&nbsp;  Image Re-tuch</a>
            <a class="dropdown-item text-warning" href="{% url 'testapp:invisble_mannequine' %}"><i class="fa fa-eye-slash" aria-hidden="true"></i>&nbsp;  Invisible Mannequin</a>
        </div>
      </div>
      <div class="col-sm-3 col-md-3">
        <div class="text-white p-2">
          <h5>HELP & ADVICE</h5>
          <a class="dropdown-item text-warning" href="{% url 'testapp:getfreedemo' %}">Get Free Quote</a>
          <a class="dropdown-item text-warning" href="{% url 'testapp:getfreedemo' %}">Free Demo</a>
          <a class="dropdown-item text-warning" href="{% url 'testapp:faq' %}">FAQs</a>
          <a class="dropdown-item text-warning" href="{% url 'testapp:pricing' %}">Pricing</a>
        </div>
      </div>
      <div class="col-sm-3 col-md-3">
        <div class="text-white p-2">
          <h5>COMPANY</h5>
          <a class="dropdown-item text-warning" href="{% url 'testapp:about' %}">About Us</a>
          <a class="dropdown-item text-warning" href="{% url 'testapp:contact' %}">Contact Us</a>
          <a class="dropdown-item text-warning" href="{% url 'testapp:bloglist' %}">Blog</a>
        </div>
      </div>
      <div class="col-sm-3 col-md-3">
        <div class="text-white p-2">
          <h5>GET IN TOUCH</h5>
          <p>Feel Free the get in touch with us on social media</p>
          <div class="text-warning">
            <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>&nbsp;
          <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>&nbsp;
          <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
          </div>
        </div>
        </div>
    </div>
    <div class="row pt-3">
      <div class="col-sm-6 col-md-6">
        <div class="text-light">
          <p>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> &nbsp;| 2021 Clipping Path India | All Right Reserved </p>
        </div>
      </div>
      <div class="col-sm-6 col-md-6">
        <div class="text-light">
          <p> Designed & Developed By <b> Brainsinfo</b></p>
        </div>
      </div>
    </div>
  </div>

</section>


<!-- GetButton.io widget for whatsapp -->
<script type="text/javascript">
  (function () {
      
      var options = {
          whatsapp: "+8801612393939", // WhatsApp number
          call_to_action: "Message us", // Call to action
          position: "right", // Position may be 'right' or 'left'
      };
      var proto = document.location.protocol, host = "getbutton.io", url = "https://static." + host;
      var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
      s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
      var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
      // alert(x);
      console.log(s);
  })();
</script>

<!-- <script>
  const scriptURL = 'https://script.google.com/macros/s/AKfycbxnNK6Dmi_MP521GzoI3MusQ15-qkMbLunJa9dNfTAZ468_zGCkq_MzgAj96V9gnHCB/exec'
const form = document.forms['google-sheet']

form.addEventListener('submit', e => {
e.preventDefault()
fetch(scriptURL, { method: 'POST', body: new FormData(form)})
 .then(response => {
   window.location.replace("https://www.softopark.com/thanks/");
 })
 .catch(error => console.error('Error!', error.message))
}) 
</script> -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>